/* Creating a trigger */

CREATE DATABASE USERS;

USE USERS;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW 
BEGIN
		
	INSERT INTO BKP_USUARIO VALUES
	(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$

DELIMITER ;

INSERT INTO USUARIO VALUES(NULL,'ANDRADE','ANDRADE2009','HEXACAMPEAO');

SELECT IDUSUARIO, NOME, LOGIN FROM USUARIO;

DELETE FROM USUARIO
WHERE IDUSUARIO = 1;

SELECT IDBACKUP, IDUSUARIO, NOME, LOGIN FROM BKP_USUARIO;

/* Creating a trigger to bkp on other database */

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2),
    EVENTO CHAR(1)
);

USE LOJA;

INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,1000,'TESTE',0.0);

SELECT IDPRODUTO, NOME, VALOR FROM LOJA.PRODUTO;

SELECT IDBKP, IDPRODUTO, NOME, VALOR, EVENTO FROM BACKUP.BKP_PRODUTO;


DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO
AFTER INSERT ON PRODUTO
FOR EACH ROW
BEGIN

    INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, NEW.IDPRODUTO, NEW.NOME, NEW.VALOR, 'I');

END
$

DELIMITER ;

INSERT INTO PRODUTO VALUES(NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO BI',80.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO ORACLE',70.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO SQL SERVER',100.00);
INSERT INTO PRODUTO VALUES(NULL,'LIVRO C#',100.00);

SELECT IDPRODUTO, NOME, VALOR FROM LOJA.PRODUTO;

SELECT IDBKP, IDPRODUTO, NOME, VALOR, EVENTO FROM BACKUP.BKP_PRODUTO;


DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO_DEL
BEFORE DELETE ON PRODUTO
FOR EACH ROW
BEGIN
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, 'D');

END
$

DELIMITER ;

DELETE FROM PRODUTO WHERE IDPRODUTO = 4;

SELECT IDPRODUTO, NOME, VALOR FROM LOJA.PRODUTO;

SELECT IDBKP, IDPRODUTO, NOME, VALOR, EVENTO FROM BACKUP.BKP_PRODUTO;


DELIMITER $

CREATE TRIGGER BACKUP_PRODUTO_UPDT
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, 'U');

END
$

DELIMITER ;

UPDATE PRODUTO SET VALOR = 75.00 WHERE IDPRODUTO = 3;

SELECT IDPRODUTO, NOME, VALOR FROM LOJA.PRODUTO;

SELECT IDBKP, IDPRODUTO, NOME, VALOR, EVENTO FROM BACKUP.BKP_PRODUTO;

/* Creating a trigger with when and who made changes */

ALTER TABLE BACKUP.BKP_PRODUTO
ADD VALOR_ORIGINAL FLOAT(10,2)

ALTER TABLE BACKUP.BKP_PRODUTO
ADD VALOR_ALTERADO FLOAT(10,2)

ALTER TABLE BACKUP.BKP_PRODUTO
ADD DATA DATETIME

ALTER TABLE BACKUP.BKP_PRODUTO
ADD USUARIO VARCHAR(30)

USE LOJA;

SELECT IDPRODUTO,  NOME, VALOR FROM PRODUTO;

DELIMITER $

CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');
	
END
$

DELIMITER ;

UPDATE PRODUTO SET VALOR = 110.00
WHERE IDPRODUTO = 4;

SELECT IDPRODUTO,  NOME, VALOR FROM PRODUTO;

SELECT IDBACKUP, IDPRODUTO, NOME, VALOR_ORIGINAL, VALOR_ALTERADO, DATA, USUARIO, EVENTO FROM BACKUP.BKP_PRODUTO;
